symfony badge fixes
dotkernel/dot-admin pull request #168
Opened 2023-06-01 16:34 UTC by cPintiuta

2023-06-01 17:30 UTC, alexmerlin requested changes
A couple of things besides my comments:
1. Please check if line endings have changed (correctly?). I see some files having every line changed, though they have the same content (I guess their line ending has been altered). This also seems to have affected some files, removing their trailing new line at the end of the file:
* .gitignore
* public/robots.txt
* src/App/templates/language/translate-text.html.twig

3. I see that you've made changes to CSS and JS files. Please run `npm run prod` in order to build their production-ready versions (`app.js` and `app.css`).

2023-06-01 17:30 UTC, alexmerlin commented on config/autoload/session.global.php
> +        'cookie_secure' => false,
This should stay `true` for production and be set to `false` only on development via `local.php`.

2023-06-01 17:30 UTC, alexmerlin commented on src/Admin/src/Factory/AuthenticationServiceFactory.php
Though it seems completely changed, this file has the same content as before.
What changed, line endings?

2023-06-01 17:30 UTC, alexmerlin commented on src/Admin/src/InputFilter/EditAdminInputFilter.php
>              'message' => '<b>Identity</b> must have between 3 and 100 characters',
I guess the message means 100 (including), so we could keep `max`=**100** before someone starts nitpicking. :)

2023-06-01 17:30 UTC, alexmerlin commented on src/App/src/Common/TimestampAwareTrait.php
> +            //save the error message
This `catch` statement will probably never be reached, but just in case, let's have here some sort of error logging (worst case scenario: `error_log($message)`). It would be a better solution then leaving a comment that we've already ignored a couple of years. :)

2023-06-01 17:30 UTC, alexmerlin commented on src/App/src/Service/IpService.php
Besides the two string param type changes, I guess the line ending changed again? Please check.

2023-06-01 17:30 UTC, alexmerlin commented on src/App/templates/app/dashboard.html.twig
Smart solution for shortening the file. 👍

2023-06-02 04:12 UTC, alexmerlin commented on src/Admin/src/Adapter/AuthenticationAdapter.php
Besides the `Admin` type hinting on `checkMethod`, I guess the line ending changed again? Please check.

2023-06-02 04:17 UTC, alexmerlin commented on src/Admin/src/InputFilter/EditAdminInputFilter.php
Any reason for having spaces around the bolded field names on some validation messages?
Let's keep either all (but then we should change in other InputFilters as well) or none with spaces.

2023-06-02 12:38 UTC, cPintiuta commented on src/Admin/src/Factory/AuthenticationServiceFactory.php
Yes. On all this pull, whenever files is entirely changed, the file line separator was CRLF, now is LF.

2023-06-02 14:58 UTC, alexmerlin commented
@cPintiuta Didn't `public/js/app.js` change as well when you ran `npm run prod`?

2023-06-06 09:07 UTC, alexmerlin approved these changes

2023-06-06 09:08 UTC, merged