Phpcs - Coding standard
dotkernel/dot-admin pull request #171
Opened 2023-06-07 15:26 UTC by cPintiuta

changed phpcs to reflex mezzio and switched from PSR12 to LaminasCodingStandard

2023-06-07 16:53 UTC, alexmerlin requested changes

2023-06-07 16:53 UTC, alexmerlin commented on composer.json
>          "squizlabs/php_codesniffer": "^3.7",
We can remove this dependency as it is required by [laminas/laminas-coding-standard/blob/2.6.x/composer.json#L15](https://github.com/laminas/laminas-coding-standard/blob/2.6.x/composer.json#L15)

2023-06-07 16:53 UTC, alexmerlin commented on phpcs.xml
> +    <exclude-pattern>test/**/TestAsset/**</exclude-pattern>
Do we need these two `exclude-pattern`s if the project does not contain those paths?

2023-06-08 17:47 UTC, alexmerlin approved these changes

2023-06-09 09:14 UTC, arhimede approved these changes

2023-06-09 09:15 UTC, merged