Di attributes
dotkernel/dot-admin pull request #245
Opened 2024-06-24 16:07 UTC by cPintiuta

2024-06-24 17:42 UTC, MarioRadu approved these changes

2024-06-25 05:02 UTC, alexmerlin requested changes
- [x] src/Admin/src/Repository/AdminLoginRepository.php:
- add `use Frontend\Admin\Entity\AdminLogin;`
- add: `#[Entity(AdminLogin::class)]`

2024-06-25 05:02 UTC, alexmerlin commented on config/config.php
>      Dot\DataFixtures\ConfigProvider::class,
```suggestion
    Dot\DataFixtures\ConfigProvider::class,
    Dot\DependencyInjection\ConfigProvider::class,
```

2024-06-25 09:54 UTC, alexmerlin approved these changes

2024-06-26 09:22 UTC, merged