Orm3
dotkernel/dot-admin pull request #253
Opened 2024-06-28 15:34 UTC by cPintiuta

2024-07-01 05:06 UTC, alexmerlin requested changes

2024-07-01 05:06 UTC, alexmerlin commented on config/autoload/doctrine.global.php
> +                    'Frontend\\App\\Entity' => 'AppEntities',
Why do we need (only) this? If it's needed, shouldn't the `Admin` entities also be listed here?
The app seems to work fine without it.

2024-07-01 05:06 UTC, alexmerlin commented on config/autoload/doctrine.global.php
> +            'AppEntities' => [
Same question as line 46.

2024-07-01 05:06 UTC, alexmerlin commented on src/App/src/Repository/AbstractRepository.php
The way I see it, the only thing this class is still useful for is that we don't need to repeat the below annotation in all our repositories:
```php
/**
 * @extends EntityRepository<object>
 */
```
Not sure though, if it's that's enough to keep it.

2024-07-01 05:06 UTC, alexmerlin commented on README.md
- in order to help our documentation builder tool with highlighting the code snippets, we should use fenced code blocks
- don't forget to modify the version number for the badge on line 6

2024-07-01 05:06 UTC, alexmerlin commented on README.md
>  [![GitHub license](https://img.shields.io/github/license/dotkernel/admin)](https://github.com/dotkernel/admin/blob/3.0/LICENSE.md)
```suggestion
[![GitHub license](https://img.shields.io/github/license/dotkernel/admin)](https://github.com/dotkernel/admin/blob/5.0/LICENSE.md)
```

2024-07-01 06:15 UTC, alexmerlin commented
Also, don't forget about [this](https://github.com/dotkernel/admin/pull/252/files#diff-62289115a627786183873ac865bc15295daeea5bfb983b28372649e71278cd8eR12) change from my unmerged PR.

2024-07-01 12:42 UTC, cPintiuta commented on config/autoload/doctrine.global.php
> +                    'Frontend\\App\\Entity' => 'AppEntities',
Those are the paths where the entities are located for the specific module, in this case for App module, for the Admin module the path is configurated in ConfigProvider of the module

2024-07-03 07:14 UTC, alexmerlin approved these changes

2024-07-03 09:15 UTC, merged