Javascript refactoring and packages updates
dotkernel/dot-admin pull request #261
Opened 2024-07-10 08:22 UTC by MarioRadu

2024-07-10 12:49 UTC, alexmerlin requested changes

2024-07-10 12:49 UTC, alexmerlin commented on src/Admin/templates/admin/list.html.twig
> +                <div class="modal-body"></div>
This way the `Message::ADMIN_DELETED_SUCCESSFULLY` message does not get displayed.

2024-07-12 06:58 UTC, alexmerlin requested changes
- `src/App/assets/js/components/*.js` - most of the files have no/multiple empty lines at the end of the file
- also, [this error](https://insight.symfony.com/projects/6a7ecfc1-a0ed-4901-96ac-d0ff61f7b55f/analyses/180) reported by SymfonyInsight

2024-07-12 12:39 UTC, cPintiuta requested changes, later dismissed

2024-07-12 12:39 UTC, cPintiuta commented on public/images/app/logo-dark.svg
this file should not exist

2024-07-12 12:39 UTC, cPintiuta commented on public/images/app/logo-light.svg
this file should not exist

2024-07-12 13:51 UTC, MarioRadu commented on public/images/app/logo-light.svg
Removed unused logo.

2024-07-12 13:51 UTC, MarioRadu commented on public/images/app/logo-dark.svg
Removed unused logo.

2024-07-14 09:47 UTC, alexmerlin approved these changes

2024-07-15 09:18 UTC, arhimede approved these changes

2024-07-15 09:22 UTC, merged