Refactored handler
dotkernel/dot-admin pull request #265
Opened 2024-07-17 07:51 UTC by MarioRadu

2024-07-17 18:40 UTC, alexmerlin requested changes

2024-07-17 18:40 UTC, alexmerlin commented on src/App/assets/js/components/_admin.js
> +        request('GET', `/admin/delete/${selections[0].uuid}`)
Why would we change this from `DELETE` to `GET`?
We should **never** use GET requests to delete a resource.

2024-07-17 18:40 UTC, alexmerlin commented on src/App/assets/js/components/_admin.js
> +        adminModal.find('.modal-messages').html('');``
```suggestion
        adminModal.find('.modal-messages').html('');
```

2024-07-17 18:40 UTC, alexmerlin commented on src/Admin/src/Controller/AdminController.php
> +    private function logErrors(Throwable $e, string $message): void
Ok, for now.
In the future, we should make this accessible across all controllers/services - probably as a trait.

2024-07-17 18:40 UTC, alexmerlin commented on src/Admin/src/RoutesDelegator.php
> +            [RequestMethodInterface::METHOD_GET, RequestMethodInterface::METHOD_POST],
See my question on `src/App/assets/js/components/_admin.js` regarding this.

2024-07-18 09:30 UTC, arhimede commented on src/App/assets/js/components/_admin.js
> +        request('GET', `/admin/delete/${selections[0].uuid}`)
@alexmerlin 
This is not an API.
Is a website, which only have GET and POST methods .
Resources we have in API"s , not in websites.

2024-07-22 10:08 UTC, arhimede commented on src/App/assets/js/components/_admin.js
> +        request('GET', `/admin/delete/${selections[0].uuid}`)
so @MarioRadu refactor de Delete form with a POST form and an extra checkbox for confirmation

2024-07-25 08:38 UTC, alexmerlin approved these changes

2024-07-25 09:07 UTC, arhimede approved these changes

2024-07-25 09:07 UTC, merged