Replaced Psalm with PHPStan
dotkernel/dot-admin pull request #302
Opened 2024-11-20 11:21 UTC by MarioRadu

2024-11-20 11:50 UTC, alexmerlin requested changes

2024-11-20 11:50 UTC, alexmerlin commented on src/Admin/src/Controller/AdminController.php
> +        protected AuthenticationService $authenticationService,
`AuthenticationServiceInterface::class,` is being `Inject`ed but now you modified the class to accept only `AuthenticationService` - (not that we should expect someone to swap it with a different implementation, but) this is against the concept of interoperability.
We should keep using `AuthenticationServiceInterface` to avoid restriction to a specific implementation.

Why were you trying to fix with this modification?

2024-11-20 12:20 UTC, MarioRadu commented on src/Admin/src/Controller/AdminController.php
> +        protected AuthenticationService $authenticationService,
`AuthenticationServiceInterface` doesn't implement the `getAdapter` and `getStorage` methods, which are used in `AdminController`, I will try a different approach.

2024-11-20 12:30 UTC, marioradu05 commented on src/Admin/src/Controller/AdminController.php
> +        protected AuthenticationService $authenticationService,
Reverted to `AuthenticationServiceInterface` and ignored the error in `phpstan.neon` config file.

2024-11-20 12:56 UTC, alexmerlin requested changes
Since you reverted to using `AuthenticationServiceInterface`, these should be reverted as well.

2024-11-20 12:56 UTC, alexmerlin commented on test/Unit/Admin/Controller/AdminControllerTest.php
> +use Laminas\Authentication\AuthenticationService;
```suggestion
use Laminas\Authentication\AuthenticationServiceInterface;
```

2024-11-20 12:56 UTC, alexmerlin commented on test/Unit/Admin/Controller/AdminControllerTest.php
> +            $this->createMock(AuthenticationService::class),
```suggestion
            $this->createMock(AuthenticationServiceInterface::class),
```

2024-11-21 07:51 UTC, alexmerlin approved these changes

2024-11-21 10:29 UTC, arhimede approved these changes

2024-11-21 10:29 UTC, merged